version: '3'
services:
    web:
        build: paymybuddy-client/
        ports:
            - "4200:4200"
        volumes:
            - "/app/node_modules"
            - ".:/app"
#exemple to add component : # docker-compose exec web ng generate component nameComponent
